package engine

import (
	"fmt"

	"keepstar/internal/domain"
)

// StampTreeIDs walks the formation and assigns stable, readable IDs
// to every atom and layout node that doesn't already have one.
// Widget IDs are preserved (already generated by engine).
// Idempotent: skips nodes that already have IDs.
func StampTreeIDs(formation *domain.FormationWithData) {
	if formation == nil {
		return
	}

	// Stamp sections if present
	for si := range formation.Sections {
		for wi := range formation.Sections[si].Widgets {
			stampWidgetIDs(&formation.Sections[si].Widgets[wi], si, wi)
		}
	}

	// Stamp top-level widgets
	for wi := range formation.Widgets {
		stampWidgetIDs(&formation.Widgets[wi], 0, wi)
	}
}

// stampWidgetIDs assigns IDs to atoms and layout nodes within a single widget.
func stampWidgetIDs(w *domain.Widget, sectionIdx, widgetIdx int) {
	prefix := fmt.Sprintf("s%d-w%d", sectionIdx, widgetIdx)

	// Stamp atom IDs
	for i := range w.AtomsV2 {
		if w.AtomsV2[i].ID != "" {
			continue
		}
		if w.AtomsV2[i].FieldName != "" {
			w.AtomsV2[i].ID = fmt.Sprintf("a-%s-%s", prefix, w.AtomsV2[i].FieldName)
		} else {
			w.AtomsV2[i].ID = fmt.Sprintf("a-%s-%d", prefix, i)
		}
	}

	// Stamp layout node IDs
	if w.Layout != nil {
		nodeCounter := 0
		stampLayoutNodeIDs(w.Layout, prefix, &nodeCounter)
	}
}

// stampLayoutNodeIDs recursively assigns IDs to layout nodes.
func stampLayoutNodeIDs(node *domain.LayoutNode, prefix string, counter *int) {
	if node == nil {
		return
	}

	if node.ID == "" {
		if node.Name != "" {
			node.ID = fmt.Sprintf("n-%s-%s", prefix, node.Name)
		} else {
			node.ID = fmt.Sprintf("n-%s-%d", prefix, *counter)
		}
	}
	*counter++

	for i := range node.Children {
		if node.Children[i].Node != nil {
			stampLayoutNodeIDs(node.Children[i].Node, prefix, counter)
		}
	}
}

// BuildTreeMap creates a compact summary of the formation tree for Agent2 context.
// Shows one widget as template + total count to minimize tokens.
// Agent2 uses field names with wildcard ops — no need to see all 50 widget IDs.
func BuildTreeMap(formation *domain.FormationWithData) map[string]interface{} {
	if formation == nil {
		return nil
	}

	// Collect all widgets (top-level + sections)
	var allWidgets []domain.Widget
	allWidgets = append(allWidgets, formation.Widgets...)
	for _, s := range formation.Sections {
		allWidgets = append(allWidgets, s.Widgets...)
	}

	if len(allWidgets) == 0 {
		return nil
	}

	// Show only the first widget as template
	template := buildWidgetMaps(allWidgets[:1])

	result := map[string]interface{}{
		"widget_template": template[0],
		"widget_count":    len(allWidgets),
	}

	if formation.Grid != nil {
		result["grid"] = map[string]int{
			"cols": formation.Grid.Cols,
			"rows": formation.Grid.Rows,
		}
	}
	if formation.Mode != "" {
		result["mode"] = string(formation.Mode)
	}

	return result
}

func buildWidgetMaps(widgets []domain.Widget) []map[string]interface{} {
	var result []map[string]interface{}
	for _, w := range widgets {
		wm := map[string]interface{}{
			"id": w.ID,
		}

		// Compact atom list: [{id, field, type}]
		var atoms []map[string]string
		for _, a := range w.AtomsV2 {
			am := map[string]string{
				"id":   a.ID,
				"type": string(a.Type),
			}
			if a.FieldName != "" {
				am["field"] = a.FieldName
			}
			atoms = append(atoms, am)
		}
		if len(atoms) > 0 {
			wm["atoms"] = atoms
		}

		// Compact layout node list
		if w.Layout != nil {
			var nodes []map[string]string
			collectLayoutNodes(w.Layout, &nodes)
			if len(nodes) > 0 {
				wm["nodes"] = nodes
			}
		}

		result = append(result, wm)
	}
	return result
}

func collectLayoutNodes(node *domain.LayoutNode, out *[]map[string]string) {
	if node == nil {
		return
	}
	nm := map[string]string{
		"id":   node.ID,
		"type": string(node.Type),
	}
	if node.Name != "" {
		nm["name"] = node.Name
	}
	*out = append(*out, nm)

	for _, ch := range node.Children {
		if ch.Node != nil {
			collectLayoutNodes(ch.Node, out)
		}
	}
}
