package handlers

import (
	"encoding/json"
	"errors"
	"net/http"

	"keepstar-admin/internal/domain"
	"keepstar-admin/internal/logger"
	"keepstar-admin/internal/usecases"
)

// MagicLinkHandler exposes the magic-link consumer endpoint. The link itself
// is generated by usecases.MagicLinkUseCase.Issue (typically from the Shopify
// install flow); the link points at a frontend page which posts the code
// here to mint a session.
type MagicLinkHandler struct {
	uc  *usecases.MagicLinkUseCase
	log *logger.Logger
}

func NewMagicLinkHandler(uc *usecases.MagicLinkUseCase, log *logger.Logger) *MagicLinkHandler {
	return &MagicLinkHandler{uc: uc, log: log}
}

// HandleConsume — POST /admin/api/auth/magic
// Body: {"code": "<token>"}.
// Public route — the signed token is the credential. Returns the same
// AuthResponse shape as Login/Google so the frontend can adopt the session
// with one code path.
func (h *MagicLinkHandler) HandleConsume(w http.ResponseWriter, r *http.Request) {
	if h.uc == nil {
		writeError(w, http.StatusNotImplemented, "magic-link not configured")
		return
	}
	if r.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "POST only")
		return
	}
	var req struct {
		Code string `json:"code"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid body")
		return
	}
	pair, user, err := h.uc.Consume(r.Context(), req.Code, r.Header.Get("User-Agent"), clientIP(r))
	if err != nil {
		if errors.Is(err, domain.ErrInvalidCredentials) {
			writeError(w, http.StatusUnauthorized, "link expired or already used")
			return
		}
		h.log.Warn("magic_link_consume_failed", "error", err)
		writeError(w, http.StatusBadRequest, "magic-link rejected")
		return
	}
	writeJSON(w, http.StatusOK, &usecases.AuthResponse{
		Token:        pair.AccessToken,
		AccessToken:  pair.AccessToken,
		RefreshToken: pair.RefreshToken,
		ExpiresIn:    pair.ExpiresIn,
		User:         user,
	})
}

// HandleConsumePendingShopLink — POST /admin/api/auth/shop-pending-link/consume
// Body: {"token": "<token>"}.
// Auth-required — the user is already signed in; this attaches the orphan
// Shopify tenant (held in the challenge's meta_json) to the current user.
// Returns {"tenant_id": "<uuid>"} so the frontend can switch workspace.
func (h *MagicLinkHandler) HandleConsumePendingShopLink(w http.ResponseWriter, r *http.Request) {
	if h.uc == nil {
		writeError(w, http.StatusNotImplemented, "pending-shop-link not configured")
		return
	}
	if r.Method != http.MethodPost {
		writeError(w, http.StatusMethodNotAllowed, "POST only")
		return
	}
	userID := UserID(r.Context())
	if userID == "" {
		writeError(w, http.StatusUnauthorized, "auth required")
		return
	}
	var req struct {
		Token string `json:"token"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid body")
		return
	}
	tenantID, err := h.uc.ConsumePendingShopLink(r.Context(), req.Token, userID)
	if err != nil {
		if errors.Is(err, domain.ErrInvalidCredentials) {
			writeError(w, http.StatusUnauthorized, "link expired or already used")
			return
		}
		h.log.Warn("shop_pending_link_consume_failed", "error", err, "user_id", userID)
		writeError(w, http.StatusBadRequest, "pending-shop-link rejected")
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{"tenant_id": tenantID})
}
