package postgres

// seedServiceProducts returns ~90 service master products.
func seedServiceProducts() []mp {
	return []mp{
		// Beauty Services - Haircare (12 products)
		{
			sku:       "BL-MENS-HAIRCUT",
			name:      "Men's Haircut",
			desc:      "Classic men's haircut with consultation",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-WOMEN-HAIRCUT",
			name:      "Women's Haircut",
			desc:      "Women's haircut with styling",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-KIDS-HAIRCUT",
			name:      "Kids' Haircut",
			desc:      "Haircut for children under 12",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-COLOR-SINGLE",
			name:      "Hair Coloring Single Color",
			desc:      "Full head single color hair dye",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-COLOR-HIGHLIGHTS",
			name:      "Hair Coloring Highlights",
			desc:      "Partial highlights with foils",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-BALAYAGE",
			name:      "Balayage",
			desc:      "Hand-painted balayage color technique",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-KERATIN",
			name:      "Keratin Treatment",
			desc:      "Keratin smoothing treatment for frizz-free hair",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-BLOWOUT",
			name:      "Hair Styling Blowout",
			desc:      "Professional blowout and styling",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-BEARD-TRIM",
			name:      "Beard Trim",
			desc:      "Beard shaping and trim with razor edge",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-EXTENSIONS",
			name:      "Hair Extensions",
			desc:      "Tape-in or clip-in hair extensions",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-SCALP-TREATMENT",
			name:      "Scalp Treatment",
			desc:      "Deep scalp cleansing and nourishing treatment",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-BRIDAL-PACKAGE",
			name:      "Bridal Package",
			desc:      "Complete bridal hair and makeup package",
			brand:     "BeautyLab",
			catSlug:   "haircare",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},

		// Beauty Services - Nail Care (7 products)
		{
			sku:       "BL-MANICURE-CLASSIC",
			name:      "Classic Manicure",
			desc:      "Classic manicure with nail shaping",
			brand:     "BeautyLab",
			catSlug:   "nail-care",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-MANICURE-GEL",
			name:      "Gel Manicure",
			desc:      "Gel polish manicure with nail shaping",
			brand:     "BeautyLab",
			catSlug:   "nail-care",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-PEDICURE-CLASSIC",
			name:      "Pedicure Classic",
			desc:      "Classic pedicure with nail care",
			brand:     "BeautyLab",
			catSlug:   "nail-care",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-PEDICURE-GEL",
			name:      "Pedicure Gel",
			desc:      "Gel polish pedicure with nail care",
			brand:     "BeautyLab",
			catSlug:   "nail-care",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"90 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-NAIL-ART",
			name:      "Nail Art Design",
			desc:      "Custom nail art design per nail",
			brand:     "BeautyLab",
			catSlug:   "nail-care",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-EYEBROW-SHAPING",
			name:      "Eyebrow Shaping",
			desc:      "Eyebrow threading and shaping",
			brand:     "BeautyLab",
			catSlug:   "nail-care",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-EYELASH-EXTENSIONS",
			name:      "Eyelash Extensions",
			desc:      "Individual eyelash extensions full set",
			brand:     "BeautyLab",
			catSlug:   "nail-care",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},

		// Beauty Services - Massage (6 products)
		{
			sku:       "BL-FACIAL-CLEANSING",
			name:      "Facial Cleansing",
			desc:      "Deep facial cleansing with extractions",
			brand:     "BeautyLab",
			catSlug:   "massage",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-FACIAL-ANTIAGING",
			name:      "Anti-aging Facial",
			desc:      "Anti-aging facial with collagen mask",
			brand:     "BeautyLab",
			catSlug:   "massage",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"90 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-FACE-MASSAGE",
			name:      "Face Massage",
			desc:      "Relaxing face and neck massage 30 min",
			brand:     "BeautyLab",
			catSlug:   "massage",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-BODY-MASSAGE-RELAX",
			name:      "Body Massage Relaxing",
			desc:      "Full body relaxing massage 60 min",
			brand:     "BeautyLab",
			catSlug:   "massage",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-BODY-MASSAGE-SPORTS",
			name:      "Body Massage Sports",
			desc:      "Deep tissue sports massage 60 min",
			brand:     "BeautyLab",
			catSlug:   "massage",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},
		{
			sku:       "BL-HOT-STONE-MASSAGE",
			name:      "Hot Stone Massage",
			desc:      "Hot stone massage therapy 90 min",
			brand:     "BeautyLab",
			catSlug:   "massage",
			images:    `["https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800"]`,
			attrs:     `{"type":"service","duration":"90 min","location":"salon"}`,
			ownerSlug: "beautylab",
		},

		// Auto Repair Services (25 products)
		{
			sku:       "AF-OIL-STANDARD",
			name:      "Oil Change Standard",
			desc:      "Standard motor oil change with filter",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-OIL-SYNTHETIC",
			name:      "Oil Change Synthetic",
			desc:      "Full synthetic oil change with filter",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-AIR-FILTER",
			name:      "Air Filter Replacement",
			desc:      "Engine air filter replacement",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"15 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-BRAKE-PADS",
			name:      "Brake Pad Replacement",
			desc:      "Front or rear brake pad replacement",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-BRAKE-DISC",
			name:      "Brake Disc Replacement",
			desc:      "Front or rear brake disc replacement",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"90 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-TIRE-MOUNT",
			name:      "Tire Mounting",
			desc:      "Mount and balance 4 tires",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"40 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-TIRE-BALANCE",
			name:      "Tire Balancing",
			desc:      "Balance 4 tires",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-WHEEL-ALIGNMENT",
			name:      "Wheel Alignment",
			desc:      "4-wheel alignment service",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"45 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-ENGINE-DIAG",
			name:      "Engine Diagnostics",
			desc:      "Full engine computer diagnostics",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-COMPUTER-DIAG",
			name:      "Computer Diagnostics",
			desc:      "OBD-II full vehicle scan",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-AC-RECHARGE",
			name:      "AC Recharge",
			desc:      "Air conditioning refrigerant recharge",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"45 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-AC-SERVICE",
			name:      "AC Full Service",
			desc:      "AC system inspection, leak check and recharge",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-PAINT-TOUCHUP",
			name:      "Body Paint Touch-up",
			desc:      "Minor scratch and chip paint repair",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-FULL-REPAINT",
			name:      "Full Body Repaint",
			desc:      "Complete vehicle body repaint",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"480 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-WASH-BASIC",
			name:      "Car Wash Basic",
			desc:      "Exterior wash with dry",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"20 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-WASH-PREMIUM",
			name:      "Car Wash Premium",
			desc:      "Full interior and exterior detail wash",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-DETAIL-INTERIOR",
			name:      "Interior Detailing",
			desc:      "Complete interior deep clean",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"180 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-DETAIL-EXTERIOR",
			name:      "Exterior Detailing",
			desc:      "Paint correction, polish and wax",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"240 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-HEADLIGHT-RESTORE",
			name:      "Headlight Restoration",
			desc:      "Headlight lens restoration and polish",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"45 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-WINDSHIELD-REPLACE",
			name:      "Windshield Replacement",
			desc:      "Full windshield replacement",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-BATTERY-REPLACE",
			name:      "Battery Replacement",
			desc:      "Car battery replacement and installation",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"20 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-SPARK-PLUGS",
			name:      "Spark Plug Replacement",
			desc:      "Replace all spark plugs",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-SUSPENSION-CHECK",
			name:      "Suspension Check",
			desc:      "Full suspension inspection and report",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-TRANSMISSION-SERVICE",
			name:      "Transmission Service",
			desc:      "Transmission fluid change and filter",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"90 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},
		{
			sku:       "AF-PREPURCHASE-INSPECT",
			name:      "Pre-purchase Inspection",
			desc:      "Comprehensive used car inspection",
			brand:     "AutoFix",
			catSlug:   "auto-repair",
			images:    `["https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800"]`,
			attrs:     `{"type":"service","duration":"90 min","location":"workshop"}`,
			ownerSlug: "autofix",
		},

		// Fitness Services - Fitness category (18 products)
		{
			sku:       "FZ-MONTHLY-GYM",
			name:      "Monthly Gym Membership",
			desc:      "Full gym access for one month",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"720 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-QUARTERLY-GYM",
			name:      "Quarterly Gym Membership",
			desc:      "Full gym access for three months",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"720 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-ANNUAL-GYM",
			name:      "Annual Gym Membership",
			desc:      "Full gym access for one year",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"720 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-GROUP-CLASS",
			name:      "Group Fitness Class",
			desc:      "Single drop-in group class",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-YOGA",
			name:      "Yoga Class",
			desc:      "Single yoga class session",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-PILATES",
			name:      "Pilates Class",
			desc:      "Single pilates class session",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-POOL-SINGLE",
			name:      "Swimming Pool Access",
			desc:      "Single pool session",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-POOL-MONTHLY",
			name:      "Swimming Monthly Pass",
			desc:      "Unlimited pool access for one month",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-CROSSFIT",
			name:      "CrossFit Class",
			desc:      "Single CrossFit class session",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-BOXING",
			name:      "Boxing Class",
			desc:      "Single boxing class session",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-CYCLING",
			name:      "Cycling Class",
			desc:      "Indoor cycling spin class",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-STRETCHING",
			name:      "Stretching Class",
			desc:      "Guided stretching and flexibility class",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-KIDS-PROGRAM",
			name:      "Kids Fitness Program",
			desc:      "Monthly kids fitness (ages 6-14)",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-SENIOR-PROGRAM",
			name:      "Senior Fitness Program",
			desc:      "Monthly senior fitness program",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-NUTRITION-CONSULT",
			name:      "Nutrition Consultation",
			desc:      "One-on-one nutrition consultation",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-BODY-COMP",
			name:      "Body Composition Analysis",
			desc:      "InBody or DEXA scan analysis",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-FITNESS-ASSESS",
			name:      "Fitness Assessment",
			desc:      "Initial fitness level assessment",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-SAUNA",
			name:      "Sauna Access",
			desc:      "Single sauna session 60 min",
			brand:     "FitZone",
			catSlug:   "fitness",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},

		// Fitness Services - Training category (2 products)
		{
			sku:       "FZ-PT-SESSION",
			name:      "Personal Training Session",
			desc:      "1-on-1 personal training 60 min",
			brand:     "FitZone",
			catSlug:   "training",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},
		{
			sku:       "FZ-PT-10PACK",
			name:      "Personal Training 10 Pack",
			desc:      "10 personal training sessions package",
			brand:     "FitZone",
			catSlug:   "training",
			images:    `["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"gym"}`,
			ownerSlug: "fitzone",
		},

		// Home Services - Cleaning (5 products)
		{
			sku:       "HS-CLEAN-STANDARD",
			name:      "Standard Apartment Cleaning",
			desc:      "1-2 bedroom apartment cleaning",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-DEEP-CLEAN",
			name:      "Deep Cleaning",
			desc:      "Thorough deep cleaning with appliances",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"240 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-OFFICE-CLEAN",
			name:      "Office Cleaning",
			desc:      "Office space cleaning per 50 sqm",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-POSTRENO-CLEAN",
			name:      "Post-renovation Cleaning",
			desc:      "Construction debris and dust removal",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"300 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-WINDOW-CLEAN",
			name:      "Window Cleaning",
			desc:      "Window cleaning per window",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"15 min","location":"home"}`,
			ownerSlug: "homeservice",
		},

		// Home Services - General (15 products)
		{
			sku:       "HS-PLUMBER-BASIC",
			name:      "Plumber Basic Visit",
			desc:      "Basic plumbing repair visit",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-PLUMBER-EMERGENCY",
			name:      "Plumber Emergency",
			desc:      "Emergency plumbing after hours",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-ELECTRICIAN-BASIC",
			name:      "Electrician Basic",
			desc:      "Basic electrical repair or installation",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-ELECTRICIAN-INSTALL",
			name:      "Electrician Installation",
			desc:      "Electrical fixture installation",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-AC-INSTALL",
			name:      "AC Installation",
			desc:      "Split system AC installation",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"180 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-FURNITURE-IKEA",
			name:      "Furniture Assembly IKEA",
			desc:      "IKEA furniture assembly per item",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-FURNITURE-CUSTOM",
			name:      "Furniture Assembly Custom",
			desc:      "Custom furniture assembly",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-TV-MOUNT",
			name:      "Wall Mounting TV",
			desc:      "TV wall mount installation",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"60 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-PAINT-ROOM",
			name:      "Painting Room",
			desc:      "Room painting up to 20 sqm",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"240 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-PAINT-APT",
			name:      "Painting Apartment",
			desc:      "Full apartment painting",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"1440 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-WALLPAPER",
			name:      "Wallpaper Installation",
			desc:      "Wallpaper hanging per room",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"240 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-FLOOR-LAMINATE",
			name:      "Floor Installation Laminate",
			desc:      "Laminate floor installation per sqm",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"30 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-APPLIANCE-INSTALL",
			name:      "Appliance Installation",
			desc:      "Major appliance installation",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"90 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-MOVING-LOCAL",
			name:      "Moving Service Local",
			desc:      "Local moving with 2 movers, 4 hours",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"240 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
		{
			sku:       "HS-HANDYMAN-2HR",
			name:      "Handyman 2 Hours",
			desc:      "General handyman service 2-hour block",
			brand:     "HomeService",
			catSlug:   "cleaning",
			images:    `["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800"]`,
			attrs:     `{"type":"service","duration":"120 min","location":"home"}`,
			ownerSlug: "homeservice",
		},
	}
}

// seedServiceListings returns service listings.
func seedServiceListings() []listing {
	return []listing{
		// Beauty Services - beautylab
		{tenantSlug: "beautylab", mpSKU: "BL-MENS-HAIRCUT", price: 150000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-WOMEN-HAIRCUT", price: 300000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-KIDS-HAIRCUT", price: 100000, stock: 999, rating: 4.9},
		{tenantSlug: "beautylab", mpSKU: "BL-COLOR-SINGLE", price: 500000, stock: 999, rating: 4.6},
		{tenantSlug: "beautylab", mpSKU: "BL-COLOR-HIGHLIGHTS", price: 600000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-BALAYAGE", price: 800000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-KERATIN", price: 700000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-BLOWOUT", price: 200000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-BEARD-TRIM", price: 80000, stock: 999, rating: 4.9},
		{tenantSlug: "beautylab", mpSKU: "BL-EXTENSIONS", price: 1500000, stock: 999, rating: 4.6},
		{tenantSlug: "beautylab", mpSKU: "BL-SCALP-TREATMENT", price: 300000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-BRIDAL-PACKAGE", price: 1200000, stock: 999, rating: 4.9},
		{tenantSlug: "beautylab", mpSKU: "BL-MANICURE-CLASSIC", price: 150000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-MANICURE-GEL", price: 250000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-PEDICURE-CLASSIC", price: 200000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-PEDICURE-GEL", price: 300000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-NAIL-ART", price: 50000, stock: 999, rating: 4.9},
		{tenantSlug: "beautylab", mpSKU: "BL-EYEBROW-SHAPING", price: 80000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-EYELASH-EXTENSIONS", price: 400000, stock: 999, rating: 4.6},
		{tenantSlug: "beautylab", mpSKU: "BL-FACIAL-CLEANSING", price: 300000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-FACIAL-ANTIAGING", price: 500000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-FACE-MASSAGE", price: 200000, stock: 999, rating: 4.9},
		{tenantSlug: "beautylab", mpSKU: "BL-BODY-MASSAGE-RELAX", price: 350000, stock: 999, rating: 4.8},
		{tenantSlug: "beautylab", mpSKU: "BL-BODY-MASSAGE-SPORTS", price: 400000, stock: 999, rating: 4.7},
		{tenantSlug: "beautylab", mpSKU: "BL-HOT-STONE-MASSAGE", price: 500000, stock: 999, rating: 4.8},

		// Auto Repair Services - autofix
		{tenantSlug: "autofix", mpSKU: "AF-OIL-STANDARD", price: 250000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-OIL-SYNTHETIC", price: 400000, stock: 999, rating: 4.7},
		{tenantSlug: "autofix", mpSKU: "AF-AIR-FILTER", price: 100000, stock: 999, rating: 4.9},
		{tenantSlug: "autofix", mpSKU: "AF-BRAKE-PADS", price: 350000, stock: 999, rating: 4.7},
		{tenantSlug: "autofix", mpSKU: "AF-BRAKE-DISC", price: 600000, stock: 999, rating: 4.6},
		{tenantSlug: "autofix", mpSKU: "AF-TIRE-MOUNT", price: 200000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-TIRE-BALANCE", price: 150000, stock: 999, rating: 4.9},
		{tenantSlug: "autofix", mpSKU: "AF-WHEEL-ALIGNMENT", price: 250000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-ENGINE-DIAG", price: 200000, stock: 999, rating: 4.7},
		{tenantSlug: "autofix", mpSKU: "AF-COMPUTER-DIAG", price: 150000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-AC-RECHARGE", price: 300000, stock: 999, rating: 4.7},
		{tenantSlug: "autofix", mpSKU: "AF-AC-SERVICE", price: 500000, stock: 999, rating: 4.6},
		{tenantSlug: "autofix", mpSKU: "AF-PAINT-TOUCHUP", price: 500000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-FULL-REPAINT", price: 5000000, stock: 999, rating: 4.5},
		{tenantSlug: "autofix", mpSKU: "AF-WASH-BASIC", price: 50000, stock: 999, rating: 4.9},
		{tenantSlug: "autofix", mpSKU: "AF-WASH-PREMIUM", price: 150000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-DETAIL-INTERIOR", price: 500000, stock: 999, rating: 4.7},
		{tenantSlug: "autofix", mpSKU: "AF-DETAIL-EXTERIOR", price: 800000, stock: 999, rating: 4.6},
		{tenantSlug: "autofix", mpSKU: "AF-HEADLIGHT-RESTORE", price: 200000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-WINDSHIELD-REPLACE", price: 800000, stock: 999, rating: 4.7},
		{tenantSlug: "autofix", mpSKU: "AF-BATTERY-REPLACE", price: 100000, stock: 999, rating: 4.9},
		{tenantSlug: "autofix", mpSKU: "AF-SPARK-PLUGS", price: 250000, stock: 999, rating: 4.8},
		{tenantSlug: "autofix", mpSKU: "AF-SUSPENSION-CHECK", price: 150000, stock: 999, rating: 4.7},
		{tenantSlug: "autofix", mpSKU: "AF-TRANSMISSION-SERVICE", price: 600000, stock: 999, rating: 4.6},
		{tenantSlug: "autofix", mpSKU: "AF-PREPURCHASE-INSPECT", price: 350000, stock: 999, rating: 4.8},

		// Fitness Services - fitzone
		{tenantSlug: "fitzone", mpSKU: "FZ-MONTHLY-GYM", price: 300000, stock: 999, rating: 4.7},
		{tenantSlug: "fitzone", mpSKU: "FZ-QUARTERLY-GYM", price: 800000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-ANNUAL-GYM", price: 2500000, stock: 999, rating: 4.9},
		{tenantSlug: "fitzone", mpSKU: "FZ-GROUP-CLASS", price: 50000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-YOGA", price: 60000, stock: 999, rating: 4.9},
		{tenantSlug: "fitzone", mpSKU: "FZ-PILATES", price: 70000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-POOL-SINGLE", price: 50000, stock: 999, rating: 4.7},
		{tenantSlug: "fitzone", mpSKU: "FZ-POOL-MONTHLY", price: 400000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-CROSSFIT", price: 80000, stock: 999, rating: 4.7},
		{tenantSlug: "fitzone", mpSKU: "FZ-BOXING", price: 70000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-CYCLING", price: 60000, stock: 999, rating: 4.9},
		{tenantSlug: "fitzone", mpSKU: "FZ-STRETCHING", price: 40000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-KIDS-PROGRAM", price: 350000, stock: 999, rating: 4.9},
		{tenantSlug: "fitzone", mpSKU: "FZ-SENIOR-PROGRAM", price: 250000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-NUTRITION-CONSULT", price: 200000, stock: 999, rating: 4.7},
		{tenantSlug: "fitzone", mpSKU: "FZ-BODY-COMP", price: 150000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-FITNESS-ASSESS", price: 100000, stock: 999, rating: 4.9},
		{tenantSlug: "fitzone", mpSKU: "FZ-SAUNA", price: 50000, stock: 999, rating: 4.8},
		{tenantSlug: "fitzone", mpSKU: "FZ-PT-SESSION", price: 300000, stock: 999, rating: 4.9},
		{tenantSlug: "fitzone", mpSKU: "FZ-PT-10PACK", price: 2500000, stock: 999, rating: 4.9},

		// Home Services - homeservice
		{tenantSlug: "homeservice", mpSKU: "HS-CLEAN-STANDARD", price: 300000, stock: 999, rating: 4.8},
		{tenantSlug: "homeservice", mpSKU: "HS-DEEP-CLEAN", price: 600000, stock: 999, rating: 4.7},
		{tenantSlug: "homeservice", mpSKU: "HS-OFFICE-CLEAN", price: 400000, stock: 999, rating: 4.8},
		{tenantSlug: "homeservice", mpSKU: "HS-POSTRENO-CLEAN", price: 800000, stock: 999, rating: 4.6},
		{tenantSlug: "homeservice", mpSKU: "HS-WINDOW-CLEAN", price: 50000, stock: 999, rating: 4.9},
		{tenantSlug: "homeservice", mpSKU: "HS-PLUMBER-BASIC", price: 200000, stock: 999, rating: 4.7},
		{tenantSlug: "homeservice", mpSKU: "HS-PLUMBER-EMERGENCY", price: 500000, stock: 999, rating: 4.6},
		{tenantSlug: "homeservice", mpSKU: "HS-ELECTRICIAN-BASIC", price: 250000, stock: 999, rating: 4.8},
		{tenantSlug: "homeservice", mpSKU: "HS-ELECTRICIAN-INSTALL", price: 400000, stock: 999, rating: 4.7},
		{tenantSlug: "homeservice", mpSKU: "HS-AC-INSTALL", price: 800000, stock: 999, rating: 4.7},
		{tenantSlug: "homeservice", mpSKU: "HS-FURNITURE-IKEA", price: 150000, stock: 999, rating: 4.9},
		{tenantSlug: "homeservice", mpSKU: "HS-FURNITURE-CUSTOM", price: 300000, stock: 999, rating: 4.8},
		{tenantSlug: "homeservice", mpSKU: "HS-TV-MOUNT", price: 200000, stock: 999, rating: 4.8},
		{tenantSlug: "homeservice", mpSKU: "HS-PAINT-ROOM", price: 500000, stock: 999, rating: 4.7},
		{tenantSlug: "homeservice", mpSKU: "HS-PAINT-APT", price: 2000000, stock: 999, rating: 4.6},
		{tenantSlug: "homeservice", mpSKU: "HS-WALLPAPER", price: 400000, stock: 999, rating: 4.7},
		{tenantSlug: "homeservice", mpSKU: "HS-FLOOR-LAMINATE", price: 50000, stock: 999, rating: 4.8},
		{tenantSlug: "homeservice", mpSKU: "HS-APPLIANCE-INSTALL", price: 250000, stock: 999, rating: 4.8},
		{tenantSlug: "homeservice", mpSKU: "HS-MOVING-LOCAL", price: 800000, stock: 999, rating: 4.7},
		{tenantSlug: "homeservice", mpSKU: "HS-HANDYMAN-2HR", price: 300000, stock: 999, rating: 4.8},
	}
}
