package postgres

// seedClothingProducts returns ~80 clothing + accessory master products.
func seedClothingProducts() []mp {
	return []mp{
		// ── Hoodies (20 products) ──────────────────────────────────────
		{
			sku:       "NIKE-TF-FULLZIP",
			name:      "Nike Tech Fleece Full-Zip Hoodie",
			desc:      "Premium full-zip hoodie with innovative Tech Fleece fabric for lightweight warmth",
			brand:     "Nike",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Grey","material":"Tech Fleece","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-CLUB-FLEECE-PO",
			name:      "Nike Club Fleece Pullover Hoodie",
			desc:      "Classic pullover hoodie with soft fleece fabric for everyday comfort",
			brand:     "Nike",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Black","material":"Cotton Fleece","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-SW-WINDRUNNER",
			name:      "Nike Sportswear Windrunner Hoodie",
			desc:      "Iconic Windrunner design with water-repellent finish and full-zip closure",
			brand:     "Nike",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Navy","material":"Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-ACG-THERMAFIT",
			name:      "Nike ACG Therma-FIT Hoodie",
			desc:      "All Conditions Gear hoodie with Therma-FIT technology for cold weather",
			brand:     "Nike",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Olive","material":"Synthetic","fit":"Relaxed"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-DRIFIT-HOODIE",
			name:      "Nike Dri-FIT Hoodie",
			desc:      "Performance hoodie with moisture-wicking Dri-FIT technology",
			brand:     "Nike",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"White","material":"Dri-FIT Fabric","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-ZNE-HOODIE",
			name:      "Adidas Z.N.E. Hoodie",
			desc:      "Zone of Non-Execution hoodie designed to help you focus and perform",
			brand:     "Adidas",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Black","material":"Recycled Polyester","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-ADICOLOR-HOODIE",
			name:      "Adidas Adicolor Classics Hoodie",
			desc:      "Retro-inspired hoodie with iconic Trefoil logo",
			brand:     "Adidas",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Grey","material":"Cotton Blend","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-TIRO24-HOODIE",
			name:      "Adidas Tiro 24 Hoodie",
			desc:      "Training hoodie with moisture-wicking AEROREADY technology",
			brand:     "Adidas",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Navy","material":"Recycled Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-ESS-3S-HOODIE",
			name:      "Adidas Essentials 3-Stripes Hoodie",
			desc:      "Classic pullover hoodie with signature 3-Stripes design",
			brand:     "Adidas",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Black","material":"Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-ESS-LOGO-HOODIE",
			name:      "Puma Essentials Big Logo Hoodie",
			desc:      "Bold hoodie featuring oversized Puma logo print",
			brand:     "Puma",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Grey","material":"Cotton Fleece","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-TEAMGOAL-HOODIE",
			name:      "Puma TeamGOAL Hoodie",
			desc:      "Training hoodie with dryCELL moisture management",
			brand:     "Puma",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Navy","material":"Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-CLOUDSPUN-HOODIE",
			name:      "Puma CLOUDSPUN Hoodie",
			desc:      "Ultra-soft hoodie with innovative CLOUDSPUN fabric",
			brand:     "Puma",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Black","material":"CLOUDSPUN","fit":"Relaxed"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-TEKNO-HOODIE",
			name:      "The North Face Tekno Hoodie",
			desc:      "Technical hoodie with FlashDry technology for superior moisture management",
			brand:     "The North Face",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Grey","material":"Synthetic Blend","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-SIMPLEDOME-HOODIE",
			name:      "The North Face Simple Dome Hoodie",
			desc:      "Classic pullover hoodie with embroidered logo",
			brand:     "The North Face",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Black","material":"Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-TREK-HOODIE",
			name:      "Columbia Trek Hoodie",
			desc:      "Outdoor hoodie with Omni-Shield water repellent technology",
			brand:     "Columbia",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Navy","material":"Polyester","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-VIEWMONT-II",
			name:      "Columbia Viewmont II Hoodie",
			desc:      "Insulated hoodie with thermal reflective lining",
			brand:     "Columbia",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Black","material":"Synthetic","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-DRY-STRETCH",
			name:      "Uniqlo DRY Stretch Hoodie",
			desc:      "Moisture-wicking hoodie with 4-way stretch fabric",
			brand:     "Uniqlo",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Grey","material":"Polyester Blend","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-ULD-PARKA",
			name:      "Uniqlo Ultra Light Down Parka Hoodie",
			desc:      "Lightweight down hoodie parka with water-repellent finish",
			brand:     "Uniqlo",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Navy","material":"Down","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "HM-RELAXED-HOODIE",
			name:      "H&M Relaxed Fit Hoodie",
			desc:      "Oversized hoodie in soft cotton blend",
			brand:     "H&M",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Beige","material":"Cotton Blend","fit":"Relaxed"}`,
			ownerSlug: "",
		},
		{
			sku:       "HM-REGULAR-HOODIE",
			name:      "H&M Regular Fit Hoodie",
			desc:      "Classic regular fit hoodie with kangaroo pocket",
			brand:     "H&M",
			catSlug:   "hoodies",
			images:    `["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800"]`,
			attrs:     `{"color":"Grey","material":"Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},

		// ── T-Shirts (15 products) ─────────────────────────────────────
		{
			sku:       "NIKE-PRO-DRIFIT-TEE",
			name:      "Nike Pro Dri-FIT T-Shirt",
			desc:      "Performance tee with sweat-wicking Dri-FIT technology",
			brand:     "Nike",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Black","material":"Dri-FIT","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-NSW-PREMIUM",
			name:      "Nike NSW Premium Essential T-Shirt",
			desc:      "Premium cotton tee with classic Nike Sportswear style",
			brand:     "Nike",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"White","material":"Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-ACG-TEE",
			name:      "Nike ACG T-Shirt",
			desc:      "All Conditions Gear tee with outdoor-inspired graphics",
			brand:     "Nike",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Olive","material":"Cotton Blend","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-OTR-TEE",
			name:      "Adidas Own The Run T-Shirt",
			desc:      "Running tee with reflective details and AEROREADY technology",
			brand:     "Adidas",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Black","material":"Recycled Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-DFT-TEE",
			name:      "Adidas Designed For Training T-Shirt",
			desc:      "Training tee with moisture-absorbing AEROREADY fabric",
			brand:     "Adidas",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Navy","material":"Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-FAV-RUN-TEE",
			name:      "Puma Favourite Running T-Shirt",
			desc:      "Lightweight running tee with dryCELL technology",
			brand:     "Puma",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Grey","material":"Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-PERF-CAT-TEE",
			name:      "Puma Performance Cat T-Shirt",
			desc:      "Performance tee with iconic Cat logo",
			brand:     "Puma",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"White","material":"Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-SIMPLEDOME-TEE",
			name:      "The North Face Simple Dome T-Shirt",
			desc:      "Classic tee with embroidered chest logo",
			brand:     "The North Face",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Black","material":"Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-HALFDOME-TEE",
			name:      "The North Face Half Dome T-Shirt",
			desc:      "Iconic Half Dome graphic tee in soft cotton",
			brand:     "The North Face",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Grey","material":"Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-ZERORULES-TEE",
			name:      "Columbia Zero Rules T-Shirt",
			desc:      "Technical tee with Omni-Wick moisture management",
			brand:     "Columbia",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Navy","material":"Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-RAPIDRIDGE",
			name:      "Columbia Rapid Ridge T-Shirt",
			desc:      "Quick-dry tee with UPF 50 sun protection",
			brand:     "Columbia",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Blue","material":"Polyester","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-SUPIMA-CREW",
			name:      "Uniqlo Supima Cotton Crew T-Shirt",
			desc:      "Premium tee made from ultra-soft Supima cotton",
			brand:     "Uniqlo",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"White","material":"Supima Cotton","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-AIRISM-CREW",
			name:      "Uniqlo AIRism Crew T-Shirt",
			desc:      "Innovative AIRism fabric for cool, dry comfort",
			brand:     "Uniqlo",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Black","material":"AIRism","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "HM-SLIM-TEE",
			name:      "H&M Slim Fit T-Shirt",
			desc:      "Fitted tee in soft cotton jersey",
			brand:     "H&M",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Grey","material":"Cotton","fit":"Slim"}`,
			ownerSlug: "",
		},
		{
			sku:       "HM-OVERSIZED-TEE",
			name:      "H&M Oversized T-Shirt",
			desc:      "Relaxed oversized tee with dropped shoulders",
			brand:     "H&M",
			catSlug:   "tshirts",
			images:    `["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800"]`,
			attrs:     `{"color":"Beige","material":"Cotton","fit":"Oversized"}`,
			ownerSlug: "",
		},

		// ── Jackets (15 products) ──────────────────────────────────────
		{
			sku:       "NIKE-STORMFIT-WR",
			name:      "Nike Storm-FIT Windrunner Jacket",
			desc:      "Weather-resistant jacket with Storm-FIT technology",
			brand:     "Nike",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Black","material":"Waterproof Fabric","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-THERMAFIT-REPEL",
			name:      "Nike Therma-FIT Repel Jacket",
			desc:      "Insulated jacket with water-repellent finish and thermal technology",
			brand:     "Nike",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Navy","material":"Synthetic Insulation","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-ACG-SIERRA-LIGHT",
			name:      "Nike ACG Sierra Light Jacket",
			desc:      "Lightweight outdoor jacket with packable design",
			brand:     "Nike",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Olive","material":"Nylon","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-TX-MULTI-RDY",
			name:      "Adidas Terrex Multi Rain.RDY Jacket",
			desc:      "Waterproof jacket with RAIN.RDY technology for outdoor adventures",
			brand:     "Adidas",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Black","material":"Waterproof Fabric","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-BSC-3S-INS",
			name:      "Adidas BSC 3-Stripes Insulated Jacket",
			desc:      "Padded jacket with iconic 3-Stripes design",
			brand:     "Adidas",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Navy","material":"Synthetic Fill","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-PACKLITE-DOWN",
			name:      "Puma PackLITE Down Jacket",
			desc:      "Lightweight down jacket that packs into its own pocket",
			brand:     "Puma",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Grey","material":"Down","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-TEAMGOAL-AW",
			name:      "Puma TeamGOAL All Weather Jacket",
			desc:      "Training jacket with water-repellent coating",
			brand:     "Puma",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Black","material":"Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-THERMOBALL-ECO",
			name:      "The North Face Thermoball Eco Jacket",
			desc:      "Synthetic insulated jacket made from recycled materials",
			brand:     "The North Face",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Black","material":"Recycled Synthetic","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-MCMURDO",
			name:      "The North Face McMurdo Parka",
			desc:      "Heavy-duty parka with down insulation and waterproof shell",
			brand:     "The North Face",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Navy","material":"Down","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-GOTHAM-III",
			name:      "The North Face Gotham III Jacket",
			desc:      "Urban parka with down insulation and removable faux fur trim",
			brand:     "The North Face",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Black","material":"Down","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-BORA-BOONEY",
			name:      "Columbia Bora Bora Booney Jacket",
			desc:      "Lightweight rain jacket with Omni-Tech waterproof breathable fabric",
			brand:     "Columbia",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Grey","material":"Waterproof Fabric","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-POWDERLITE",
			name:      "Columbia Powder Lite Jacket",
			desc:      "Insulated jacket with thermal reflective lining",
			brand:     "Columbia",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Navy","material":"Synthetic Insulation","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-BUGABOO-II",
			name:      "Columbia Bugaboo II Jacket",
			desc:      "3-in-1 interchange jacket with removable liner",
			brand:     "Columbia",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Black","material":"Waterproof Shell","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-ULD-JACKET",
			name:      "Uniqlo Ultra Light Down Jacket",
			desc:      "Incredibly lightweight down jacket that packs small",
			brand:     "Uniqlo",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Grey","material":"Down","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-HYBRID-DOWN",
			name:      "Uniqlo Hybrid Down Parka",
			desc:      "Parka with down-filled body and stretch sleeves",
			brand:     "Uniqlo",
			catSlug:   "jackets",
			images:    `["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800"]`,
			attrs:     `{"color":"Navy","material":"Down/Stretch","fit":"Regular"}`,
			ownerSlug: "",
		},

		// ── Pants (10 products) ────────────────────────────────────────
		{
			sku:       "NIKE-CLUB-JOGGERS",
			name:      "Nike Club Fleece Joggers",
			desc:      "Comfortable fleece joggers with tapered fit",
			brand:     "Nike",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Grey","material":"Cotton Fleece","fit":"Tapered"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-SW-CARGO",
			name:      "Nike Sportswear Cargo Pants",
			desc:      "Modern cargo pants with multiple pockets and adjustable cuffs",
			brand:     "Nike",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Black","material":"Cotton Blend","fit":"Relaxed"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-TIRO24",
			name:      "Adidas Tiro 24 Training Pants",
			desc:      "Soccer-inspired training pants with tapered fit and zip pockets",
			brand:     "Adidas",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Navy","material":"Recycled Polyester","fit":"Tapered"}`,
			ownerSlug: "",
		},
		{
			sku:       "ADIDAS-ESS-FLEECE-TAP",
			name:      "Adidas Essentials Fleece Tapered Pants",
			desc:      "Comfortable fleece pants with ribbed cuffs",
			brand:     "Adidas",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Grey","material":"Cotton Fleece","fit":"Tapered"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-TEAMGOAL-TRAIN",
			name:      "Puma TeamGOAL Training Pants",
			desc:      "Performance training pants with dryCELL technology",
			brand:     "Puma",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Black","material":"Polyester","fit":"Athletic"}`,
			ownerSlug: "",
		},
		{
			sku:       "PUMA-ESS-SLIM",
			name:      "Puma Essentials Slim Pants",
			desc:      "Slim fit pants with side stripe detail",
			brand:     "Puma",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Navy","material":"Cotton Blend","fit":"Slim"}`,
			ownerSlug: "",
		},
		{
			sku:       "TNF-PARAMOUNT-CONV",
			name:      "The North Face Paramount Trail Convertible Pants",
			desc:      "Versatile pants that convert to shorts with zip-off legs",
			brand:     "The North Face",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Khaki","material":"Nylon","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "COLUMBIA-SR-CONV",
			name:      "Columbia Silver Ridge Convertible Pants",
			desc:      "Outdoor pants with UPF 50 and convertible legs",
			brand:     "Columbia",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Grey","material":"Nylon","fit":"Regular"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-SMART-ANKLE",
			name:      "Uniqlo Smart Ankle Pants",
			desc:      "Modern ankle-length pants with clean tailoring",
			brand:     "Uniqlo",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Black","material":"Polyester Blend","fit":"Slim"}`,
			ownerSlug: "",
		},
		{
			sku:       "UNIQLO-ULTRA-ACTIVE",
			name:      "Uniqlo Ultra Stretch Active Pants",
			desc:      "4-way stretch pants for maximum mobility",
			brand:     "Uniqlo",
			catSlug:   "pants",
			images:    `["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800"]`,
			attrs:     `{"color":"Navy","material":"Stretch Fabric","fit":"Athletic"}`,
			ownerSlug: "",
		},

		// ── Accessories (20 products) ──────────────────────────────────
		{
			sku:       "SAMSONITE-GUARDIT",
			name:      "Samsonite Guardit Backpack",
			desc:      "Professional laptop backpack with smart organization and protection",
			brand:     "Samsonite",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","capacity":"15.6 inch","material":"Polyester"}`,
			ownerSlug: "",
		},
		{
			sku:       "JANSPORT-SUPERBREAK",
			name:      "JanSport SuperBreak Backpack",
			desc:      "Classic daypack with iconic design and durable construction",
			brand:     "JanSport",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Navy","capacity":"25L","material":"Polyester"}`,
			ownerSlug: "",
		},
		{
			sku:       "HERSCHEL-LA",
			name:      "Herschel Little America Backpack",
			desc:      "Mountain-inspired backpack with modern functionality",
			brand:     "Herschel",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","capacity":"25L","material":"Polyester"}`,
			ownerSlug: "",
		},
		{
			sku:       "OSPREY-DAYLITE",
			name:      "Osprey Daylite Backpack",
			desc:      "Versatile daypack perfect for hiking and everyday use",
			brand:     "Osprey",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Grey","capacity":"13L","material":"Nylon"}`,
			ownerSlug: "",
		},
		{
			sku:       "NIKE-BRASILIA-95",
			name:      "Nike Brasilia 9.5 Backpack",
			desc:      "Training backpack with multiple compartments and durable design",
			brand:     "Nike",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","capacity":"24L","material":"Polyester"}`,
			ownerSlug: "",
		},
		{
			sku:       "APPLE-MAGSAFE-CASE",
			name:      "Apple MagSafe Clear Case",
			desc:      "Official MagSafe compatible clear case with scratch resistance",
			brand:     "Apple",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Clear","compatible":"iPhone","material":"Polycarbonate"}`,
			ownerSlug: "",
		},
		{
			sku:       "SAMSUNG-CLEARVIEW",
			name:      "Samsung Clear View Cover",
			desc:      "Smart cover with translucent front for notifications",
			brand:     "Samsung",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","compatible":"Galaxy","material":"Polycarbonate"}`,
			ownerSlug: "",
		},
		{
			sku:       "SPIGEN-TOUGH-ARMOR",
			name:      "Spigen Tough Armor Case",
			desc:      "Military-grade protection with dual-layer design",
			brand:     "Spigen",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","protection":"Military Grade","material":"TPU"}`,
			ownerSlug: "",
		},
		{
			sku:       "OTTERBOX-DEFENDER",
			name:      "OtterBox Defender Series Case",
			desc:      "Multi-layer protection with port covers and holster clip",
			brand:     "OtterBox",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","protection":"Heavy Duty","material":"Polycarbonate"}`,
			ownerSlug: "",
		},
		{
			sku:       "ANKER-PB20K",
			name:      "Anker PowerCore 20000 Power Bank",
			desc:      "High-capacity power bank with fast charging for multiple devices",
			brand:     "Anker",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","capacity":"20000mAh","ports":"2 USB"}`,
			ownerSlug: "",
		},
		{
			sku:       "XIAOMI-MI-PB10K",
			name:      "Xiaomi Mi Power Bank 10000mAh",
			desc:      "Compact power bank with aluminum casing and dual USB ports",
			brand:     "Xiaomi",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Silver","capacity":"10000mAh","ports":"2 USB"}`,
			ownerSlug: "",
		},
		{
			sku:       "SAMSUNG-25W-ADAPTER",
			name:      "Samsung 25W Travel Adapter",
			desc:      "Fast charging travel adapter with USB-C Power Delivery",
			brand:     "Samsung",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"White","power":"25W","connector":"USB-C"}`,
			ownerSlug: "",
		},
		{
			sku:       "APPLE-20W-USBC",
			name:      "Apple 20W USB-C Power Adapter",
			desc:      "Compact fast charger for iPhone and iPad",
			brand:     "Apple",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"White","power":"20W","connector":"USB-C"}`,
			ownerSlug: "",
		},
		{
			sku:       "ANKER-65W-GAN",
			name:      "Anker 65W GaN Charger",
			desc:      "Compact GaN charger with 3 ports for laptops and phones",
			brand:     "Anker",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","power":"65W","ports":"2 USB-C, 1 USB-A"}`,
			ownerSlug: "",
		},
		{
			sku:       "BELKIN-3IN1-WIRELESS",
			name:      "Belkin 3-in-1 Wireless Charger",
			desc:      "Charge iPhone, Apple Watch, and AirPods simultaneously",
			brand:     "Belkin",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"White","devices":"3","type":"Wireless"}`,
			ownerSlug: "",
		},
		{
			sku:       "APPLE-USBC-LIGHTNING",
			name:      "Apple USB-C to Lightning Cable",
			desc:      "Official 1m cable for fast charging and data sync",
			brand:     "Apple",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"White","length":"1m","connector":"USB-C to Lightning"}`,
			ownerSlug: "",
		},
		{
			sku:       "ANKER-USBC-CABLE",
			name:      "Anker USB-C Cable",
			desc:      "Durable braided USB-C cable with 10000+ bend lifespan",
			brand:     "Anker",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","length":"1.8m","connector":"USB-C to USB-C"}`,
			ownerSlug: "",
		},
		{
			sku:       "UGREEN-USBC-HUB",
			name:      "Ugreen USB-C Hub",
			desc:      "7-in-1 USB-C hub with HDMI, USB 3.0, SD card reader",
			brand:     "Ugreen",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Grey","ports":"7","features":"HDMI, USB, SD"}`,
			ownerSlug: "",
		},
		{
			sku:       "APPLE-AIRTAG",
			name:      "Apple AirTag",
			desc:      "Precision tracking device with Find My network",
			brand:     "Apple",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"White","battery":"CR2032","connectivity":"Bluetooth"}`,
			ownerSlug: "",
		},
		{
			sku:       "SAMSUNG-SMARTTAG2",
			name:      "Samsung SmartTag 2",
			desc:      "Bluetooth tracker with compass view and lost mode",
			brand:     "Samsung",
			catSlug:   "accessories",
			images:    `["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800"]`,
			attrs:     `{"color":"Black","battery":"CR2032","connectivity":"Bluetooth"}`,
			ownerSlug: "",
		},
	}
}

// seedClothingListings returns clothing + accessory listings.
func seedClothingListings() []listing {
	return []listing{
		// ── Nike Hoodies ───────────────────────────────────────────────
		{tenantSlug: "nike", mpSKU: "NIKE-TF-FULLZIP", price: 7990, stock: 45, rating: 4.8},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-TF-FULLZIP", price: 7590, stock: 30, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-TF-FULLZIP", price: 7990, stock: 25, rating: 4.8},

		{tenantSlug: "nike", mpSKU: "NIKE-CLUB-FLEECE-PO", price: 3990, stock: 60, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-CLUB-FLEECE-PO", price: 3790, stock: 50, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-CLUB-FLEECE-PO", price: 3990, stock: 40, rating: 4.6},

		{tenantSlug: "nike", mpSKU: "NIKE-SW-WINDRUNNER", price: 5990, stock: 35, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-SW-WINDRUNNER", price: 5690, stock: 40, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-SW-WINDRUNNER", price: 5990, stock: 30, rating: 4.7},

		{tenantSlug: "nike", mpSKU: "NIKE-ACG-THERMAFIT", price: 6990, stock: 25, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-ACG-THERMAFIT", price: 6640, stock: 20, rating: 4.6},

		{tenantSlug: "nike", mpSKU: "NIKE-DRIFIT-HOODIE", price: 4490, stock: 50, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-DRIFIT-HOODIE", price: 4270, stock: 45, rating: 4.5},

		// ── Adidas Hoodies ─────────────────────────────────────────────
		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-ZNE-HOODIE", price: 6990, stock: 40, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-ZNE-HOODIE", price: 6990, stock: 35, rating: 4.7},

		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-ADICOLOR-HOODIE", price: 4990, stock: 55, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-ADICOLOR-HOODIE", price: 4990, stock: 50, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-TIRO24-HOODIE", price: 4490, stock: 60, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-TIRO24-HOODIE", price: 4490, stock: 45, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-ESS-3S-HOODIE", price: 3990, stock: 70, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-ESS-3S-HOODIE", price: 3990, stock: 60, rating: 4.5},

		// ── Other Brand Hoodies ────────────────────────────────────────
		{tenantSlug: "sportmaster", mpSKU: "PUMA-ESS-LOGO-HOODIE", price: 3990, stock: 50, rating: 4.4},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-ESS-LOGO-HOODIE", price: 3990, stock: 45, rating: 4.4},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-TEAMGOAL-HOODIE", price: 4490, stock: 40, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-TEAMGOAL-HOODIE", price: 4490, stock: 35, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-CLOUDSPUN-HOODIE", price: 5490, stock: 30, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-CLOUDSPUN-HOODIE", price: 5490, stock: 25, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "TNF-TEKNO-HOODIE", price: 7990, stock: 25, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "TNF-TEKNO-HOODIE", price: 7990, stock: 20, rating: 4.7},

		{tenantSlug: "sportmaster", mpSKU: "TNF-SIMPLEDOME-HOODIE", price: 5990, stock: 35, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "TNF-SIMPLEDOME-HOODIE", price: 5990, stock: 30, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-TREK-HOODIE", price: 5490, stock: 30, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-TREK-HOODIE", price: 5490, stock: 25, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-VIEWMONT-II", price: 6990, stock: 25, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-VIEWMONT-II", price: 6990, stock: 20, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-DRY-STRETCH", price: 2990, stock: 80, rating: 4.4},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-DRY-STRETCH", price: 2990, stock: 70, rating: 4.4},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-ULD-PARKA", price: 5990, stock: 40, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-ULD-PARKA", price: 5990, stock: 35, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "HM-RELAXED-HOODIE", price: 2490, stock: 90, rating: 4.3},
		{tenantSlug: "fashionhub", mpSKU: "HM-RELAXED-HOODIE", price: 2490, stock: 85, rating: 4.3},

		{tenantSlug: "sportmaster", mpSKU: "HM-REGULAR-HOODIE", price: 1990, stock: 100, rating: 4.2},
		{tenantSlug: "fashionhub", mpSKU: "HM-REGULAR-HOODIE", price: 1990, stock: 95, rating: 4.2},

		// ── Nike T-Shirts ──────────────────────────────────────────────
		{tenantSlug: "nike", mpSKU: "NIKE-PRO-DRIFIT-TEE", price: 2490, stock: 80, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-PRO-DRIFIT-TEE", price: 2370, stock: 75, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-PRO-DRIFIT-TEE", price: 2490, stock: 70, rating: 4.7},

		{tenantSlug: "nike", mpSKU: "NIKE-NSW-PREMIUM", price: 1990, stock: 90, rating: 4.5},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-NSW-PREMIUM", price: 1890, stock: 85, rating: 4.4},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-NSW-PREMIUM", price: 1990, stock: 80, rating: 4.5},

		{tenantSlug: "nike", mpSKU: "NIKE-ACG-TEE", price: 2290, stock: 60, rating: 4.5},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-ACG-TEE", price: 2180, stock: 55, rating: 4.4},

		// ── Other Brand T-Shirts ───────────────────────────────────────
		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-OTR-TEE", price: 2490, stock: 70, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-OTR-TEE", price: 2490, stock: 65, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-DFT-TEE", price: 2290, stock: 75, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-DFT-TEE", price: 2290, stock: 70, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-FAV-RUN-TEE", price: 1990, stock: 80, rating: 4.4},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-FAV-RUN-TEE", price: 1990, stock: 75, rating: 4.4},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-PERF-CAT-TEE", price: 1790, stock: 85, rating: 4.3},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-PERF-CAT-TEE", price: 1790, stock: 80, rating: 4.3},

		{tenantSlug: "sportmaster", mpSKU: "TNF-SIMPLEDOME-TEE", price: 2990, stock: 60, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "TNF-SIMPLEDOME-TEE", price: 2990, stock: 55, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "TNF-HALFDOME-TEE", price: 2790, stock: 65, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "TNF-HALFDOME-TEE", price: 2790, stock: 60, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-ZERORULES-TEE", price: 2290, stock: 70, rating: 4.4},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-ZERORULES-TEE", price: 2290, stock: 65, rating: 4.4},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-RAPIDRIDGE", price: 2490, stock: 65, rating: 4.4},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-RAPIDRIDGE", price: 2490, stock: 60, rating: 4.4},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-SUPIMA-CREW", price: 1490, stock: 120, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-SUPIMA-CREW", price: 1490, stock: 110, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-AIRISM-CREW", price: 1290, stock: 130, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-AIRISM-CREW", price: 1290, stock: 120, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "HM-SLIM-TEE", price: 990, stock: 150, rating: 4.2},
		{tenantSlug: "fashionhub", mpSKU: "HM-SLIM-TEE", price: 990, stock: 140, rating: 4.2},

		{tenantSlug: "sportmaster", mpSKU: "HM-OVERSIZED-TEE", price: 1190, stock: 140, rating: 4.3},
		{tenantSlug: "fashionhub", mpSKU: "HM-OVERSIZED-TEE", price: 1190, stock: 130, rating: 4.3},

		// ── Nike Jackets ───────────────────────────────────────────────
		{tenantSlug: "nike", mpSKU: "NIKE-STORMFIT-WR", price: 9990, stock: 30, rating: 4.8},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-STORMFIT-WR", price: 9490, stock: 25, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-STORMFIT-WR", price: 9990, stock: 20, rating: 4.8},

		{tenantSlug: "nike", mpSKU: "NIKE-THERMAFIT-REPEL", price: 8990, stock: 35, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-THERMAFIT-REPEL", price: 8540, stock: 30, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-THERMAFIT-REPEL", price: 8990, stock: 25, rating: 4.7},

		{tenantSlug: "nike", mpSKU: "NIKE-ACG-SIERRA-LIGHT", price: 7990, stock: 25, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-ACG-SIERRA-LIGHT", price: 7590, stock: 20, rating: 4.5},

		// ── Other Brand Jackets ────────────────────────────────────────
		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-TX-MULTI-RDY", price: 11990, stock: 20, rating: 4.8},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-TX-MULTI-RDY", price: 11990, stock: 15, rating: 4.8},

		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-BSC-3S-INS", price: 7990, stock: 30, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-BSC-3S-INS", price: 7990, stock: 25, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-PACKLITE-DOWN", price: 6990, stock: 35, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-PACKLITE-DOWN", price: 6990, stock: 30, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-TEAMGOAL-AW", price: 5990, stock: 40, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-TEAMGOAL-AW", price: 5990, stock: 35, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "TNF-THERMOBALL-ECO", price: 12990, stock: 20, rating: 4.8},
		{tenantSlug: "fashionhub", mpSKU: "TNF-THERMOBALL-ECO", price: 12990, stock: 15, rating: 4.8},

		{tenantSlug: "sportmaster", mpSKU: "TNF-MCMURDO", price: 24990, stock: 10, rating: 4.8},
		{tenantSlug: "fashionhub", mpSKU: "TNF-MCMURDO", price: 24990, stock: 8, rating: 4.8},

		{tenantSlug: "sportmaster", mpSKU: "TNF-GOTHAM-III", price: 19990, stock: 15, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "TNF-GOTHAM-III", price: 19990, stock: 12, rating: 4.7},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-BORA-BOONEY", price: 8990, stock: 25, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-BORA-BOONEY", price: 8990, stock: 20, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-POWDERLITE", price: 9990, stock: 25, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-POWDERLITE", price: 9990, stock: 20, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-BUGABOO-II", price: 14990, stock: 15, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-BUGABOO-II", price: 14990, stock: 12, rating: 4.7},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-ULD-JACKET", price: 4990, stock: 50, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-ULD-JACKET", price: 4990, stock: 45, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-HYBRID-DOWN", price: 6990, stock: 40, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-HYBRID-DOWN", price: 6990, stock: 35, rating: 4.6},

		// ── Nike Pants ─────────────────────────────────────────────────
		{tenantSlug: "nike", mpSKU: "NIKE-CLUB-JOGGERS", price: 3990, stock: 60, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-CLUB-JOGGERS", price: 3790, stock: 55, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-CLUB-JOGGERS", price: 3990, stock: 50, rating: 4.6},

		{tenantSlug: "nike", mpSKU: "NIKE-SW-CARGO", price: 5990, stock: 40, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "NIKE-SW-CARGO", price: 5690, stock: 35, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-SW-CARGO", price: 5990, stock: 30, rating: 4.7},

		// ── Other Brand Pants ──────────────────────────────────────────
		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-TIRO24", price: 4990, stock: 55, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-TIRO24", price: 4990, stock: 50, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "ADIDAS-ESS-FLEECE-TAP", price: 3990, stock: 60, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "ADIDAS-ESS-FLEECE-TAP", price: 3990, stock: 55, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-TEAMGOAL-TRAIN", price: 3990, stock: 50, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-TEAMGOAL-TRAIN", price: 3990, stock: 45, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "PUMA-ESS-SLIM", price: 3490, stock: 55, rating: 4.4},
		{tenantSlug: "fashionhub", mpSKU: "PUMA-ESS-SLIM", price: 3490, stock: 50, rating: 4.4},

		{tenantSlug: "sportmaster", mpSKU: "TNF-PARAMOUNT-CONV", price: 6990, stock: 30, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "TNF-PARAMOUNT-CONV", price: 6990, stock: 25, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "COLUMBIA-SR-CONV", price: 5990, stock: 35, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "COLUMBIA-SR-CONV", price: 5990, stock: 30, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-SMART-ANKLE", price: 2990, stock: 70, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-SMART-ANKLE", price: 2990, stock: 65, rating: 4.5},

		{tenantSlug: "sportmaster", mpSKU: "UNIQLO-ULTRA-ACTIVE", price: 3490, stock: 60, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "UNIQLO-ULTRA-ACTIVE", price: 3490, stock: 55, rating: 4.5},

		// ── Accessories ────────────────────────────────────────────────
		{tenantSlug: "techstore", mpSKU: "SAMSONITE-GUARDIT", price: 5990, stock: 30, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "SAMSONITE-GUARDIT", price: 5990, stock: 25, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "SAMSONITE-GUARDIT", price: 5990, stock: 20, rating: 4.7},

		{tenantSlug: "techstore", mpSKU: "JANSPORT-SUPERBREAK", price: 3990, stock: 40, rating: 4.5},
		{tenantSlug: "sportmaster", mpSKU: "JANSPORT-SUPERBREAK", price: 3990, stock: 35, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "JANSPORT-SUPERBREAK", price: 3990, stock: 30, rating: 4.5},

		{tenantSlug: "techstore", mpSKU: "HERSCHEL-LA", price: 7990, stock: 25, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "HERSCHEL-LA", price: 7990, stock: 20, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "HERSCHEL-LA", price: 7990, stock: 20, rating: 4.7},

		{tenantSlug: "techstore", mpSKU: "OSPREY-DAYLITE", price: 4990, stock: 30, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "OSPREY-DAYLITE", price: 4990, stock: 25, rating: 4.6},

		{tenantSlug: "sportmaster", mpSKU: "NIKE-BRASILIA-95", price: 2990, stock: 50, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "NIKE-BRASILIA-95", price: 2990, stock: 45, rating: 4.5},

		{tenantSlug: "techstore", mpSKU: "APPLE-MAGSAFE-CASE", price: 4990, stock: 60, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "APPLE-MAGSAFE-CASE", price: 4990, stock: 50, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "APPLE-MAGSAFE-CASE", price: 4990, stock: 40, rating: 4.6},

		{tenantSlug: "techstore", mpSKU: "SAMSUNG-CLEARVIEW", price: 3990, stock: 55, rating: 4.5},
		{tenantSlug: "sportmaster", mpSKU: "SAMSUNG-CLEARVIEW", price: 3990, stock: 45, rating: 4.5},

		{tenantSlug: "techstore", mpSKU: "SPIGEN-TOUGH-ARMOR", price: 2490, stock: 80, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "SPIGEN-TOUGH-ARMOR", price: 2490, stock: 70, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "SPIGEN-TOUGH-ARMOR", price: 2490, stock: 60, rating: 4.6},

		{tenantSlug: "techstore", mpSKU: "OTTERBOX-DEFENDER", price: 3990, stock: 50, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "OTTERBOX-DEFENDER", price: 3990, stock: 40, rating: 4.7},

		{tenantSlug: "techstore", mpSKU: "ANKER-PB20K", price: 3990, stock: 70, rating: 4.8},
		{tenantSlug: "sportmaster", mpSKU: "ANKER-PB20K", price: 3990, stock: 60, rating: 4.8},
		{tenantSlug: "fashionhub", mpSKU: "ANKER-PB20K", price: 3990, stock: 50, rating: 4.8},

		{tenantSlug: "techstore", mpSKU: "XIAOMI-MI-PB10K", price: 1990, stock: 90, rating: 4.5},
		{tenantSlug: "sportmaster", mpSKU: "XIAOMI-MI-PB10K", price: 1990, stock: 80, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "XIAOMI-MI-PB10K", price: 1990, stock: 70, rating: 4.5},

		{tenantSlug: "techstore", mpSKU: "SAMSUNG-25W-ADAPTER", price: 1990, stock: 100, rating: 4.5},
		{tenantSlug: "sportmaster", mpSKU: "SAMSUNG-25W-ADAPTER", price: 1990, stock: 80, rating: 4.5},

		{tenantSlug: "techstore", mpSKU: "APPLE-20W-USBC", price: 2490, stock: 90, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "APPLE-20W-USBC", price: 2490, stock: 75, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "APPLE-20W-USBC", price: 2490, stock: 60, rating: 4.6},

		{tenantSlug: "techstore", mpSKU: "ANKER-65W-GAN", price: 4990, stock: 60, rating: 4.8},
		{tenantSlug: "sportmaster", mpSKU: "ANKER-65W-GAN", price: 4990, stock: 50, rating: 4.8},

		{tenantSlug: "techstore", mpSKU: "BELKIN-3IN1-WIRELESS", price: 9990, stock: 30, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "BELKIN-3IN1-WIRELESS", price: 9990, stock: 25, rating: 4.7},

		{tenantSlug: "techstore", mpSKU: "APPLE-USBC-LIGHTNING", price: 1990, stock: 120, rating: 4.5},
		{tenantSlug: "sportmaster", mpSKU: "APPLE-USBC-LIGHTNING", price: 1990, stock: 100, rating: 4.5},
		{tenantSlug: "fashionhub", mpSKU: "APPLE-USBC-LIGHTNING", price: 1990, stock: 80, rating: 4.5},

		{tenantSlug: "techstore", mpSKU: "ANKER-USBC-CABLE", price: 1290, stock: 150, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "ANKER-USBC-CABLE", price: 1290, stock: 130, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "ANKER-USBC-CABLE", price: 1290, stock: 110, rating: 4.6},

		{tenantSlug: "techstore", mpSKU: "UGREEN-USBC-HUB", price: 3990, stock: 70, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "UGREEN-USBC-HUB", price: 3990, stock: 60, rating: 4.6},

		{tenantSlug: "techstore", mpSKU: "APPLE-AIRTAG", price: 2990, stock: 80, rating: 4.7},
		{tenantSlug: "sportmaster", mpSKU: "APPLE-AIRTAG", price: 2990, stock: 70, rating: 4.7},
		{tenantSlug: "fashionhub", mpSKU: "APPLE-AIRTAG", price: 2990, stock: 60, rating: 4.7},

		{tenantSlug: "techstore", mpSKU: "SAMSUNG-SMARTTAG2", price: 2490, stock: 75, rating: 4.6},
		{tenantSlug: "sportmaster", mpSKU: "SAMSUNG-SMARTTAG2", price: 2490, stock: 65, rating: 4.6},
		{tenantSlug: "fashionhub", mpSKU: "SAMSUNG-SMARTTAG2", price: 2490, stock: 55, rating: 4.6},
	}
}
